### ISSUE TITLE
Valet 4.0 Upgrade Error: "PHP Fatal error:  Uncaught Error: Class "Symfony\Component\EventDispatcher\Event" not found"

### ISSUE THREAD

**Issue by zeshanshani** [laravel/valet#1400]
### Description

After upgrading to Laravel Valet 4 using composer, the `valet install` or any other `valet` command throws following errors:

```
PHP Deprecated:  Return type of Symfony\Component\Process\Process::getIterator($flags = 0) should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zeshan/.composer/vendor/symfony/process/Process.php on line 567

Deprecated: Return type of Symfony\Component\Process\Process::getIterator($flags = 0) should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zeshan/.composer/vendor/symfony/process/Process.php on line 567
PHP Deprecated:  Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zeshan/.composer/vendor/symfony/console/Helper/HelperSet.php on line 104

Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/zeshan/.composer/vendor/symfony/console/Helper/HelperSet.php on line 104
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\EventDispatcher\Event" not found in /Users/zeshan/.composer/vendor/symfony/console/Event/ConsoleEvent.php:24
Stack trace:
#0 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(582): include()
#1 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/Users/zeshan/....')
#2 /Users/zeshan/.composer/vendor/symfony/console/Event/ConsoleCommandEvent.php(19): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(582): include('/Users/zeshan/....')
#4 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/Users/zeshan/....')
#5 /Users/zeshan/.composer/vendor/symfony/console/Application.php(1003): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#6 /Users/zeshan/.composer/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\Command\ListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/zeshan/.composer/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/zeshan/.composer/vendor/laravel/valet/cli/valet.php(9): Symfony\Component\Console\Application->run()
#9 {main}
  thrown in /Users/zeshan/.composer/vendor/symfony/console/Event/ConsoleEvent.php on line 24

Fatal error: Uncaught Error: Class "Symfony\Component\EventDispatcher\Event" not found in /Users/zeshan/.composer/vendor/symfony/console/Event/ConsoleEvent.php:24
Stack trace:
#0 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(582): include()
#1 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/Users/zeshan/....')
#2 /Users/zeshan/.composer/vendor/symfony/console/Event/ConsoleCommandEvent.php(19): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#3 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(582): include('/Users/zeshan/....')
#4 /Users/zeshan/.composer/vendor/composer/ClassLoader.php(433): Composer\Autoload\{closure}('/Users/zeshan/....')
#5 /Users/zeshan/.composer/vendor/symfony/console/Application.php(1003): Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')
#6 /Users/zeshan/.composer/vendor/symfony/console/Application.php(255): Symfony\Component\Console\Application->doRunCommand(Object(Symfony\Component\Console\Command\ListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /Users/zeshan/.composer/vendor/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/zeshan/.composer/vendor/laravel/valet/cli/valet.php(9): Symfony\Component\Console\Application->run()
#9 {main}
  thrown in /Users/zeshan/.composer/vendor/symfony/console/Event/ConsoleEvent.php on line 24
```

This error most specifically:

```
PHP Fatal error:  Uncaught Error: Class "Symfony\Component\EventDispatcher\Event" not found in /Users/zeshan/.composer/vendor/symfony/console/Event/ConsoleEvent.php:24
```

I have following many solutions including:

- Upgrading/reinstalling composer
- Updating PHP to 8.2.x and ensuring the version is correct everywhere
- Upgrading all the brew packages
- Upgrading all the composer packages
- Removing all the configs of valet from `~/.config/valet`

Nothing seems to resolve the issue. Any help would be appreciated. Happy to provide more info if needed. 

### Steps To Reproduce

- Upgrade Laravel valet to 4 using `composer global require laravel/valet`
- Running `valet install`

### Diagnosis

Unable to run any valet command as all of them throws same errors.

**Comment by mattstauffer** [comment]
@zeshanshani I'm guessing this has to do with a different global dependency that you have that's locking you to a specific version of some Symfony component. I'm not 100% sure which would cause this particular error, though. I'll try to dig into it.

**Comment by drbyte** [comment]
Please post the contents of your `/Users/zeshan/.composer/composer.json` file.

**Comment by zeshanshani** [comment]
@drbyte here are the contents:

```
{
    "require": {
        "laravel/homestead": "~2.0",
        "squizlabs/php_codesniffer": "*",
        "laravel/installer": "^2.3",
        "laravel/valet": "^2"
    }
}
```

@mattstauffer happy to help debugging this in any way possible

**Comment by zeshanshani** [comment]
@mattstauffer @drbyte 

Thanks for pointing me at the composer.json file, it was indeed "laravel/homestead" package which was causing the issue. After removing that package, valet 4 is working fine now. 

Thanks!

**Comment by drbyte** [comment]
@zeshanshani 

Glad you sorted it out!

Please close this issue if it's resolved for you. Thanks!
