### ISSUE TITLE
Can't share sites anymore

### ISSUE THREAD

**Issue by huludini** [laravel/valet#189]
Sometimes I try to run `valet share`, I get the following error.

```
failed MSpanList_Insert 0xa75cb0 0x301a89377a 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.MSpanList_Insert(0x983090, 0xa75cb0)
	/Users/aes/src/ngrok/toolchain/src/runtime/mheap.c:692 +0x8f
runtime.MHeap_Alloc(0x9817c0, 0x1, 0x10000000008, 0x61ba9)
	/Users/aes/src/ngrok/toolchain/src/runtime/mheap.c:240 +0x66
runtime.MCentral_CacheSpan(0x9889f8, 0xc2080eb680)
	/Users/aes/src/ngrok/toolchain/src/runtime/mcentral.c:85 +0x167
runtime.MCache_Refill(0xa6f4b0, 0xc200000008, 0xc208068240)
	/Users/aes/src/ngrok/toolchain/src/runtime/mcache.c:90 +0xa0

goroutine 23 [running]:
runtime.switchtoM()
	/Users/aes/src/ngrok/toolchain/src/runtime/asm_amd64.s:198 fp=0xc20816b618 sp=0xc20816b610
runtime.mallocgc(0x70, 0x5c5600, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/runtime/malloc.go:178 +0x849 fp=0xc20816b6c8 sp=0xc20816b618
runtime.newobject(0x5c5600, 0x2)
	/Users/aes/src/ngrok/toolchain/src/runtime/malloc.go:353 +0x49 fp=0xc20816b6f0 sp=0xc20816b6c8
net.socket(0x636350, 0x3, 0x2, 0x1, 0x0, 0xc208170000, 0xa83598, 0x0, 0xa83598, 0xc208170090, ...)
	/Users/aes/src/ngrok/toolchain/src/net/sock_posix.go:48 +0x178 fp=0xc20816b7c0 sp=0xc20816b6f0
net.internetSocket(0x636350, 0x3, 0xa83598, 0x0, 0xa83598, 0xc208170090, 0xe7791f70f, 0x0, 0x970420, 0x1, ...)
	/Users/aes/src/ngrok/toolchain/src/net/ipsock_posix.go:137 +0x148 fp=0xc20816b848 sp=0xc20816b7c0
net.dialTCP(0x636350, 0x3, 0x0, 0xc208170090, 0xe7791f70f, 0x0, 0x970420, 0xc20816b940, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/tcpsock_posix.go:156 +0x125 fp=0xc20816b978 sp=0xc20816b848
net.dialSingle(0x636350, 0x3, 0xc20801ef00, 0x17, 0x0, 0x0, 0xa83530, 0xc208170090, 0xe7791f70f, 0x0, ...)
	/Users/aes/src/ngrok/toolchain/src/net/dial.go:235 +0x3f5 fp=0xc20816bac8 sp=0xc20816b978
net.func·016(0xe7791f70f, 0xe00000000, 0x970420, 0x0, 0x0, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/dial.go:163 +0x12c fp=0xc20816bb80 sp=0xc20816bac8
net.dial(0x636350, 0x3, 0xa83530, 0xc208170090, 0xc20816bcd8, 0xe7791f70f, 0xe00000000, 0x970420, 0x0, 0x0, ...)
	/Users/aes/src/ngrok/toolchain/src/net/fd_unix.go:40 +0x6f fp=0xc20816bbc0 sp=0xc20816bb80
net.(*Dialer).Dial(0xc20800b680, 0x636350, 0x3, 0xc20801ef00, 0x17, 0x0, 0x0, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/dial.go:170 +0x4be fp=0xc20816bd08 sp=0xc20816bbc0
main.func·035(0x0, 0x0, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/tunnel_session.go:316 +0xce fp=0xc20816be50 sp=0xc20816bd08
lib/tunnel/client.(*reconnectingSession).connect(0xc20800b700, 0x0, 0x0, 0x0, 0x0)
	/Users/aes/src/ngrok/src/lib/tunnel/client/reconnecting.go:224 +0x402 fp=0xc20816bf98 sp=0xc20816be50
lib/tunnel/client.func·001()
	/Users/aes/src/ngrok/src/lib/tunnel/client/reconnecting.go:106 +0x43 fp=0xc20816bfe0 sp=0xc20816bf98
runtime.goexit()
	/Users/aes/src/ngrok/toolchain/src/runtime/asm_amd64.s:2232 +0x1 fp=0xc20816bfe8 sp=0xc20816bfe0
created by lib/tunnel/client.NewReconnectingSession
	/Users/aes/src/ngrok/src/lib/tunnel/client/reconnecting.go:111 +0x2d8

goroutine 1 [chan receive]:
main.(*controller).Run(0xc2080ff110, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/controller.go:118 +0xc53
main.cliCommonStart(0xc2080a40e0, 0xc20810a180, 0xc2080c7660, 0x1, 0x1)
	/Users/aes/src/ngrok/src/ngrok/cli.go:265 +0xe8
main.runHTTP(0xc2080a40e0)
	/Users/aes/src/ngrok/src/ngrok/cli.go:156 +0x41f
github.com/inconshreveable/axiom.func·001(0xc2080a40e0)
	/Users/aes/src/ngrok/vendor/src/github.com/inconshreveable/axiom/axiom.go:122 +0x325
github.com/codegangsta/cli.Command.Run(0x62a4d0, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x697450, 0x14, 0x763250, ...)
	/Users/aes/src/ngrok/vendor/src/github.com/codegangsta/cli/command.go:118 +0x1044
github.com/codegangsta/cli.(*App).Run(0xc20800c0f0, 0xc20800a000, 0x4, 0x4, 0x0, 0x0)
	/Users/aes/src/ngrok/vendor/src/github.com/codegangsta/cli/app.go:177 +0xeaa
main.main()
	/Users/aes/src/ngrok/src/ngrok/main.go:11 +0x68

goroutine 6 [syscall]:
os/signal.loop()
	/Users/aes/src/ngrok/toolchain/src/os/signal/signal_unix.go:21 +0x1f
created by os/signal.init·1
	/Users/aes/src/ngrok/toolchain/src/os/signal/signal_unix.go:27 +0x35

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/Users/aes/src/ngrok/toolchain/src/runtime/asm_amd64.s:2232 +0x1

goroutine 9 [select]:
main.func·004()
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:24 +0x418
created by main.NewBroadcast
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:39 +0x1d8

goroutine 34 [select]:
main.(*tunnelSession).notifier(0xc20805aa80)
	/Users/aes/src/ngrok/src/ngrok/tunnel_session.go:454 +0x290
created by main.(*tunnelSession).Run
	/Users/aes/src/ngrok/src/ngrok/tunnel_session.go:272 +0x6f

goroutine 10 [select]:
main.func·005()
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:76 +0x280
created by main.NewBitcast
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:94 +0x1d8

goroutine 11 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x970300)
	/Users/aes/src/ngrok/vendor/src/github.com/rcrowley/go-metrics/meter.go:221 +0x52
created by github.com/rcrowley/go-metrics.NewMeter
	/Users/aes/src/ngrok/vendor/src/github.com/rcrowley/go-metrics/meter.go:40 +0x1f7

goroutine 12 [select]:
main.func·005()
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:76 +0x280
created by main.NewBitcast
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:94 +0x1d8

goroutine 13 [select]:
main.func·004()
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:24 +0x418
created by main.NewBroadcast
	/Users/aes/src/ngrok/src/ngrok/broadcast.go:39 +0x1d8

goroutine 14 [select]:
main.publish(0xc2080a2ec0, 0xc20805aa80, 0xa82c50, 0xc20805a720, 0xa83148, 0xc2080a4460)
	/Users/aes/src/ngrok/src/ngrok/web_ui.go:242 +0xa95
created by main.webSocket
	/Users/aes/src/ngrok/src/ngrok/web_ui.go:197 +0xaf

goroutine 15 [chan receive]:
main.(*defaultStorage).Run(0xc20805a720, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/storage.go:297 +0x64
main.func·009()
	/Users/aes/src/ngrok/src/ngrok/controller.go:105 +0x219
created by main.(*controller).Run
	/Users/aes/src/ngrok/src/ngrok/controller.go:114 +0xbe9

goroutine 16 [chan receive]:
main.(*tunnelSession).Run(0xc20805aa80, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/tunnel_session.go:278 +0xd7
main.func·009()
	/Users/aes/src/ngrok/src/ngrok/controller.go:105 +0x219
created by main.(*controller).Run
	/Users/aes/src/ngrok/src/ngrok/controller.go:114 +0xbe9

goroutine 18 [chan receive]:
main.(*defaultUpdater).Run(0xc2080a4460, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/updater.go:189 +0x70
main.func·009()
	/Users/aes/src/ngrok/src/ngrok/controller.go:105 +0x219
created by main.(*controller).Run
	/Users/aes/src/ngrok/src/ngrok/controller.go:114 +0xbe9

goroutine 19 [IO wait]:
net.(*pollDesc).Wait(0xc20816c060, 0x72, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc20816c060, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc20816c000, 0x0, 0xa80df8, 0xc20814e050)
	/Users/aes/src/ngrok/toolchain/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208174000, 0xc2080e0700, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208174000, 0x0, 0x0, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/tcpsock_posix.go:244 +0x4c
net/http.(*Server).Serve(0xc208178000, 0xa83560, 0xc208174000, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/http/server.go:1728 +0x92
net/http.Serve(0xa83560, 0xc208174000, 0xa845f8, 0xc20800b4c0, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/net/http/server.go:1606 +0xa1
main.(*web).Run(0xc2080f4210, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/web.go:49 +0x2f1
main.func·009()
	/Users/aes/src/ngrok/src/ngrok/controller.go:105 +0x219
created by main.(*controller).Run
	/Users/aes/src/ngrok/src/ngrok/controller.go:114 +0xbe9

goroutine 20 [chan receive]:
main.(*signalHandler).Run(0xc2080ee8f0, 0x0, 0x0)
	/Users/aes/src/ngrok/src/ngrok/signal.go:23 +0x104
main.func·009()
	/Users/aes/src/ngrok/src/ngrok/controller.go:105 +0x219
created by main.(*controller).Run
	/Users/aes/src/ngrok/src/ngrok/controller.go:114 +0xbe9

goroutine 21 [runnable]:
os.(*File).Read(0xc208176000, 0xc20817a000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/os/file.go:91
io.Copy(0xa84690, 0xc208144100, 0xa84668, 0xc208176000, 0x5c0000, 0x0, 0x0)
	/Users/aes/src/ngrok/toolchain/src/io/io.go:362 +0x1f6
github.com/equinox-io/equinox.computeChecksum(0xc208092540, 0x35, 0x0, 0x0)
	/Users/aes/src/ngrok/vendor/src/github.com/equinox-io/equinox/sdk.go:227 +0x153
github.com/equinox-io/equinox.Check(0x64f1d0, 0xe, 0x6353b0, 0x6, 0x0, 0x0, 0xc208092540, 0x35, 0x0, 0x5b6e80, ...)
	/Users/aes/src/ngrok/vendor/src/github.com/equinox-io/equinox/sdk.go:160 +0x328
main.(*defaultUpdater).run(0xc2080a4460)
	/Users/aes/src/ngrok/src/ngrok/updater.go:108 +0x165
created by main.(*defaultUpdater).Run
	/Users/aes/src/ngrok/src/ngrok/updater.go:188 +0x44

goroutine 22 [chan receive]:
main.(*tunnelSession).handleSessionUpdates(0xc20805aa80, 0xc20805b800)
	/Users/aes/src/ngrok/src/ngrok/tunnel_session.go:489 +0x96
created by main.(*tunnelSession).start
	/Users/aes/src/ngrok/src/ngrok/tunnel_session.go:359 +0x70c
Toms-iMac:beltway Irons$ 
                                                                                                                            
  [Httpful\Exception\ConnectionErrorException]                                                                              
  Unable to connect to "http://127.0.0.1:4040/api/tunnels": 7 Failed to connect to 127.0.0.1 port 4040: Connection refused  
                                                                                                                            

fetch-share-url
```
The other times when it works and after someone is viewing the site for about 5 seconds, the tunnel then drops unexpectedly. I can see that the tunnel needs to be updated, but when I hit `control + u` it gives me a blank black screen.

I'm on Sierra 10.12.

Any help would be greatly appreciated.

**Comment by huludini** [comment]
As far as I'm concerned, I've fixed the issue. It was with ngrok not being updated to the latest version, so I manually downloaded the latest and moved it to the valet bin folder.

**Comment by bplus** [comment]
FWIW, I solved this problem in the same way.

**Comment by itzikbenh** [comment]
I had the same issue. I Added the new ngrok and now the error is "404-not found". Any ideas?

**Comment by knightazura** [comment]
Dude, where I can find "valet bin" folder to store latest ngrok file??

**Comment by whoacowboy** [comment]
2+ years later, and the solution still works! Woo hoo!

**Comment by drbyte** [comment]
Note: In Nov 2018 the release of Valet 2.1.2 updated the ngrok binary to "2.2.8" ... which is still the most current as of today.
